function z = countAligned(alignment)

% input: alignment generated by swalign function

countergapseq1 = 0;
countergapseq2 = 0;
countermismatch = 0;

for i = 1:size(alignment,2)
    if alignment(1,i) == '-' 
        countergapseq1 = countergapseq1 + 1;
    end
    
    if alignment(3,i) == '-' 
        countergapseq2 = countergapseq2 + 1;
    end
    
    if alignment(1,i) ~= alignment(3,i)
        countermismatch = countermismatch + 1;
    end
    
end

totalGaps = countergapseq1 + countergapseq2 + countermismatch;
seqAlignLength = size(alignment, 2) - totalGaps;

fractionAlign = seqAlignLength/size(alignment,2);

z = ['Fraction aligned is: ' num2str(fractionAlign)];

end
